name: aipainapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  flutter_login_facebook: ^1.9.0
  google_sign_in: ^6.1.5
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  uni_links: ^0.5.1
  flutter_dotenv: ^5.1.0
  jaguar_jwt: ^3.0.0
  flutter_svg: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - .env
